In [3]:
import numpy as np
GRAVITY = 9.8

In [4]:
path = "../data/raw/accelertions/heave_regular/heave_regular_H060.csv"

data = np.loadtxt(path, delimiter=",", skiprows=1)

print(data.shape)
print(data[:5])

(19200, 4)
[[ 0.00000000e+00  4.33680869e-19  1.73472348e-18 -1.89941509e+00]
 [ 6.25000000e-02  4.33680869e-19  0.00000000e+00 -1.87563083e+00]
 [ 1.25000000e-01  4.33680869e-19  8.67361738e-19 -1.80475867e+00]
 [ 1.87500000e-01  4.33680869e-19  0.00000000e+00 -1.68877490e+00]
 [ 2.50000000e-01  1.08420217e-19  0.00000000e+00 -1.53086109e+00]]


In [5]:
vert_acc = (
    np.sqrt(
        data[:,1]**2 +
        data[:,2]**2 +
        data[:,3]**2
    )
    - GRAVITY
)